# Generated by Django 3.2 on 2022-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='temp', max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
