# Generated by Django 3.2 on 2022-05-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_order_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderElements',
            new_name='OrderElement',
        ),
    ]
