# Generated by Django 3.2 on 2022-05-13 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220505_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(default='снят с продажи', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
