# Generated by Django 3.2 on 2022-05-15 11:13

from django.db import migrations
from copy_prices import copy_prices_to_orders


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderelement_price'),
    ]

    operations = [
         migrations.RunPython(copy_prices_to_orders),
    ]
