# Generated by Django 3.2 on 2022-05-15 12:20

from django.db import migrations
from foodcartapp.copy_prices import copy_prices_to_orders


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220515_1613'),
    ]

    operations = [
        migrations.RunPython(copy_prices_to_orders),
    ]
