# Generated by Django 3.2 on 2022-05-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    def copy_prices_to_orders(apps, schema_editor):
        OrderElement = apps.get_model('foodcartapp', 'OrderElement')
        order_elements = OrderElement.objects.all()
        for order_element in order_elements.iterator():
            order_element.price = order_element.product.price
            order_element.save()

    dependencies = [
        ('foodcartapp', '0044_auto_20220515_1613'),
    ]

    operations = [
        migrations.RunPython(copy_prices_to_orders),
    ]
