# Generated by Django 3.2 on 2022-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220515_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Обработанный заказ'), ('UNPROCESSED', 'Необработанный заказ')], db_index=True, default='UNPROCESSED', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
