# Generated by Django 3.2 on 2022-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20220517_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('EPAY', 'EPAY')], db_index=True, default='EPAY', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
