# Generated by Django 3.2 on 2022-05-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaraunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('EPAY', 'Электронно')], db_index=True, default='EPAY', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
