# Generated by Django 3.2 on 2022-05-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220518_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaraunt',
            new_name='restaurant',
        ),
    ]
