# Generated by Django 3.2 on 2022-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_restaraunt_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Обработанный заказ'), ('COOKING', 'Готовится заказ'), ('UNPROCESSED', 'Необработанный заказ')], db_index=True, default='UNPROCESSED', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
