# Generated by Django 3.2 on 2022-06-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderelement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_elements', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
