# Generated by Django 3.2 on 2022-06-20 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получены в'),
        ),
    ]
