# Generated by Django 3.2 on 2022-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20220620_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
